version: '3'
services:
  adjust_challenge:
    container_name: adjust_challenge
    command: rails server -p 3000 -b '0.0.0.0'
    image: adjust_challenge
    build: .
    environment:
      - PGHOST=db
      - PGUSER=postgres
    ports :
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
    networks:
      - adjust
  db:
    container_name: adjust_challenge_db
    image: postgres:10.5
    ports :
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/tmp
    networks:
      - adjust
networks:
  adjust:

volumes:
  postgres_data:
